version: '3.7'

services:
  transaction-service:
    build: ./transaction-service
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  analysis-service:
    build: ./analysis-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
